### NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11],
              [3, 10],
              [1, 7]])

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = np.mean(a, axis=0)

In [5]:
mean_a

array([2. , 8.4])

In [6]:
centered_a = a - mean_a

In [7]:
centered_a

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [8]:
a_centered_sp = centered_a[:,0] @ centered_a[:,1]

In [9]:
a_centered_sp

8.0

In [10]:
a_centered_sp / (a.shape[0] - 1)

2.0

In [11]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

### Pandas

In [12]:
import pandas as pd

In [13]:
authors = pd.DataFrame({'author_id' : [1, 2, 3],
                        'author_name' : ['Тургенев', 'Чехов', 'Островский']},
                        columns = ['author_id', 'author_name'])

In [14]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [15]:
books = pd.DataFrame({'author_id' : [1, 1, 1, 2, 2, 3, 3],
                     'book_tittle' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price' : [450, 300, 350, 500, 450, 370, 290]}, columns = ['author_id', 'book_tittle', 'price'])

In [16]:
books

author_id           book_tittle  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [17]:
authors_price = pd.merge(authors, books, on = 'author_id')

In [18]:
authors_price

author_id author_name           book_tittle  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [19]:
top5 = authors_price.sort_values(by = 'price', ascending = False).head()

In [20]:
top5

author_id author_name        book_tittle  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [33]:
authors_stat = authors_price.groupby('author_name').agg({'price': ['min', 'max', 'mean']})

In [32]:
authors_stat

price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000

In [23]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [24]:
authors_price

author_id author_name           book_tittle  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [28]:
book_info = authors_price.pivot_table(index='author_name', columns='cover', values='price', aggfunc='sum', fill_value=0)

In [29]:
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950