### NumPy

In [68]:
import numpy as np

In [8]:
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11],
              [3, 10],
              [1, 7]])

In [42]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [9]:
mean_a = np.mean(a, axis=0)

In [50]:
mean_a

array([2. , 8.4])

In [14]:
centered_a = a - mean_a

In [15]:
centered_a

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [16]:
a_centered_sp = centered_a[:,0] @ centered_a[:,1]

In [17]:
a_centered_sp

8.0

In [18]:
a_centered_sp / (a.shape[0] - 1)

2.0

In [19]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

### Pandas

In [3]:
import pandas as pd

In [4]:
authors = pd.DataFrame({'author_id' : [1, 2, 3],
                        'author_name' : ['Тургенев', 'Чехов', 'Островский']},
                        columns = ['author_id', 'author_name'])

In [5]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [6]:
books = pd.DataFrame({'author_id' : [1, 1, 1, 2, 2, 3, 3],
                     'book_tittle' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price' : [450, 300, 350, 500, 450, 370, 290]}, columns = ['author_id', 'book_tittle', 'price'])

In [7]:
books

author_id           book_tittle  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [9]:
authors_price = pd.merge(authors, books, on = 'author_id')

In [32]:
authors_price

author_id author_name           book_tittle  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [43]:
top5 = authors_price.sort_values(by = 'price', ascending = False).head()

In [45]:
top5

author_id author_name        book_tittle  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [60]:
authors_stat = authors_price.groupby('author_name').agg(max_price=('price', 'max'),min_price=('price', 'min'), mean_price=('price', 'mean'))

In [61]:
authors_stat

max_price  min_price  mean_price
author_name                                  
Островский         370        290  330.000000
Тургенев           450        300  366.666667
Чехов              500        450  475.000000

In [64]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [65]:
authors_price

author_id author_name           book_tittle  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [76]:
book_info = authors_price.pivot_table(values='cover', index=['author_name'], columns=['твердая', 'мягкая'], aggfunc=np.sum, fill_value=0)

KeyError: 'твердая'